[balancer]
51.250.45.51

[bastion]
89.169.155.184
# ssh ubuntu@89.169.155.184
# 10.0.1.32

[web_servers]
web-a
# ssh ubuntu@web-a -J ubuntu@89.169.155.184
# 10.0.1.19

web-b
# ssh ubuntu@web-b -J ubuntu@89.169.155.184
# 10.0.2.32

[web_servers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q ubuntu@89.169.155.184"'

[zabbix_servers]
zabbix
# ssh ubuntu@zabbix -J ubuntu@89.169.155.184
# http://89.169.134.141/zabbix		(user Admin)
# 10.0.1.25

[zabbix_servers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q ubuntu@89.169.155.184"'

[elastic_servers]
es
# ssh ubuntu@es -J ubuntu@89.169.155.184
# curl -X GET http://10.0.1.30:9200
# 10.0.1.30

[elastic_servers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q ubuntu@89.169.155.184"'

[kibana_servers]
kibana
# ssh ubuntu@kibana -J ubuntu@89.169.155.184
# http://46.21.247.185:5601/		(user elastic)
# 10.0.1.33

[kibana_servers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q ubuntu@89.169.155.184"'
