---
- name: Обновить SSH ключи для группы хостов
  hosts: all
  gather_facts: no
  vars:
    target_group: "all"
    known_hosts_path: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"

  tasks:
    - name: Удалить старые ключи хостов из known_hosts
      ansible.builtin.known_hosts:
        path: "{{ known_hosts_path }}"
        name: "{{ item }}"
        state: absent
      loop: "{{ groups[target_group] }}"

- name: Проверить доступность хостов
  hosts: all
  gather_facts: no

  tasks:
    - name: Ping
      ping:
